//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDE_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDE_Errors
    {
        public int ErrorId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> App { get; set; }
        public string Method { get; set; }
        public string Class { get; set; }
        public string Message { get; set; }
    }
}
