//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDE_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDE_Parts
    {
        public int PartId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string EAN { get; set; }
        public Nullable<int> ProducerId { get; set; }
        public string ProducentsCode { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Symbol { get; set; }
        public string Destination { get; set; }
        public string Appliance { get; set; }
        public string UsedOn { get; set; }
        public string Token { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> LmBy { get; set; }
        public Nullable<System.DateTime> LmOn { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string Image { get; set; }
    }
}
