//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDE_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDE_Logs
    {
        public int LogId { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Description { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    }
}
