//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDE_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDE_ActionTypes
    {
        public int ActionTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<bool> MesSync { get; set; }
        public Nullable<bool> ShowInPlanning { get; set; }
        public Nullable<bool> RequireInitialDiagnosis { get; set; }
        public Nullable<bool> AllowDuplicates { get; set; }
        public Nullable<bool> RequireQrToStart { get; set; }
        public Nullable<bool> RequireQrToFinish { get; set; }
        public Nullable<bool> ClosePreviousInSamePlace { get; set; }
    }
}
