//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDE_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDE_DeliveryItems
    {
        public int DeliveryItemId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public Nullable<int> PartId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> StorageBinId { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
