//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDE_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDE_Tenants
    {
        public int TenantId { get; set; }
        public string TenantName { get; set; }
        public string TenantFullName { get; set; }
        public string TenantToken { get; set; }
    }
}
