//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDE_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDE_Handlings
    {
        public int HandlingId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.DateTime> FinishedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsFrozen { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string Output { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
